config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :ricetudies
  resources :comments
  get 'home/index'
  root to: 'home#index'
  
  resources :eateries do
    post "/like", to: "likes#like_toggle"
  end
  
  resources :promotions do
    post "/like", to: "likes#like_toggle2"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @eatery = Eatery.all
    @ranking = Eatery.joins(:likes).group("likes.eatery_id").order("count(likes.eatery_id) desc").limit(10)
    
    @promotions = Promotion.order("created_at desc").limit(10)
    
    @ricetudies = Ricetudy.order("created_at desc").limit(10)
    
    @comments = Comment.order("created_at desc").limit(10)
      
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
        <div class="col s12 m3">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">thumb_up</i></h2>
            <h5 class="center">Likes</h5>
                <ol>
                  <% @ranking.each do |r| %>
                    <li>
                      <%= link_to eatery_path(r) do%>
                        <%= r.name %>
                      <% end %>
                        <%= r.likes.size %><br>
                      <% end %>
                </li>
                </ol>
            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m3">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">today</i></h2>
            <h5 class="center">Promotions</h5>
                <ol>
                  <% @promotions.each do |p| %>
                    <li>
                    <%= link_to promotion_path(p) do%>
                      |<%= p.restaurant%>|
                      <%= p.name %><br>
                    <% end %>
                    </li>
                  <% end %>
                </ol>
            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m3">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">mode_edit</i></h2>
            <h5 class="center">Study</h5>
                <ol>
                <% @ricetudies.each do |r| %>
                  <li>
                  <%= link_to ricetudy_path(r) do%>
                    <%= r.title %><br>
                  <% end %>
                    <%= r.content %><br>
                  <% end %>
                  </li>
                </ol>
            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
        
        <div class="col s12 m3">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">comment</i></h2>
            <h5 class="center">Reviews</h5>
              <ol>

              <% @comments.each do |c|%>
              <% if c.eatery_id.present?%>
              <li>
              <%= link_to eatery_path(c.eatery_id) do%>
              <%= c.content%><br>
              <%end%>
              </li>
              <% elsif c.promotion_id.present?%>
              <li>
              <%= link_to promotion_path(c.promotion_id) do%>
              <%= c.content%><br>
              <%end%>
              </li>
              <%# else%>
              <li>
              <%#= link_to ricetudy_path(c.ricetudy_id) do%>
              <%#= c.content%><br>
              <%#end%>
              </li>
              <%end%>
              <%end%>
              
              
              </ol>
            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>