config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :ricetudies
  resources :comments
  get 'home/index'
  root to: 'home#index'
  
  resources :eateries do
    post "/like", to: "likes#like_toggle"
  end
  
  resources :promotions do
    post "/like", to: "likes#like_toggle2"
  end

end

app/models/eatery.rb
class Eatery < ActiveRecord::Base
    
    resourcify
    
  include Authority::Abilities

   mount_uploader :image, AvatarUploader
   
    #Eatery:Comment => 1:N
    has_many :comments
    
    belongs_to :user, required: false
    
    # Eatery : Promotion => 1:N
    has_many :promotions
    
    # Eatery : Like => 1:N
    has_many :likes

    # Eatery : User => M:N
    has_many :liked_users, through: :likes, source: :user
    
    searchable do
        text :menu, :boost => 5
        text :style
        text :name#,:publish_month
        text :comments do
            comments.map(&:eatery)
        end
        #time :published_at
        #string :publish_month
end
    
end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:index]
    
    def index
        @search = Eatery.search do
        fulltext params[:search]
        end
        
        if params[:search].present? 
            @eateries = @search.results
        else
            @eateries = Eatery.order("name asc").paginate(:page => params[:page], :per_page => 28)
        end
        #@eateries = @search.results
        
        #@eateries = Eatery.paginate(:page => params[:page], :per_page => 30)
        #if @search.present?
            #@eateries = @search.results
        #else
            #@eateries = Eatery.paginate(:page => params[:page], :per_page => 30)
        #end
    end

    def new
        @eatery = Eatery.new
    end

    def create
        @eatery = Eatery.new(eatery_params)
        @eatery.user=current_user
        @eatery.save
    
        redirect_to eatery_path(@eatery)
        
    end
    
    def show
        @eatery = Eatery.find(params[:id])

    end

    def edit
        @eatery = Eatery.find(params[:id])
        #authorize_action_for @eatery
    end

    def update
        @eatery = Eatery.find(params[:id])    
        #authorize_action_for @eatery
        @eatery.update(eatery_params)
        
        redirect_to eatery_path(@eatery)
    end

    def destroy
        #authorize_action_for @eatery
        @eatery = Eatery.find(params[:id])
        @eatery.destroy
        
        redirect_to eateries_path
    end
    
    private
    def eatery_params
        params.require(:eatery).permit(:style, :name, :callnumber, :openhourm, :menu, :image)    
    end

end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/views/eateries/_form.html.erb
<div class="field">
    <%= f.label :style %>
    <%= f.text_field :style %>
</div>

<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>

<div class="field">
    <%= f.label :callnumber %>
    <%= f.text_field :callnumber %>
</div>

<div class="field">
    <%= f.label :openhour %>
    <%= f.text_field :openhour %>
</div>

<div class="field">
    <%= f.label :menu %>
    <%= f.text_area :menu %>
</div>

<div class="field">
<%=f.label :image  %>
<%=f.file_field :image%>
</div>

<%=f.submit "올리기", class:"btn waves-effect waves-light" %>

app/views/eateries/edit.html.erb
<%=  form_for @eatery, multipart: true do |a|%>
<%= render partial:'form' , locals: {:f=>a}%> 
<%end%>

app/views/eateries/index.html.erb
        

<%=link_to "new", new_eatery_path ,class: 'waves-effect waves-light btn'%><br>
  <% @eateries.each do |e| %>
      <div class="col s12 m3">
        <div class="card">
            <div class="card-image">
            <%= image_tag "#{e.image}", :size => '200x150' %>
          
            </div>
            <div class="card-content">
            <span class="card-title"><h5><%=e.name%></h5></span><br>
              <%= e.likes.size %> 명이
              <% if user_signed_in? %>
                <% if current_user.is_like(e) %>
                  <%= link_to eatery_like_path(e), method: "post" do%>
                    <%= image_tag "#{asset_path "heart.png"}", alt: "blog-img"%>
                  <% end %>
                <% else %>
                  <%= link_to eatery_like_path(e), method: "post" do%>
                    <%= image_tag "#{asset_path "heart_empty.png"}", alt: "blog-img"%>
                  <% end %>
                <% end %>
              <% end %>합니다.  
              <p><%= truncate(e.menu, :length => 14, :separator=>' ')%></p>
            </div>
            <div class="card-action">
              <% unless e.user.nil? %>
              user: <%=e.user.email%><br>
              <%end%>
              contact: <%=e.callnumber%><br>
              openhour: <%=e.openhour%><br>
              <%=link_to "show", eatery_path(e), class: 'waves-effect waves-light btn'%>
            </div>
          </div>
        </div>
  <%end%>      
            <%= will_paginate @eateries %>
      

app/views/eateries/new.html.erb
<h1>Eatery-New</h1>
<%= form_for @eatery, multipart: true do |a| %>
<%= render partial: 'form', locals: {:f => a} %>  
<% end %>

app/views/eateries/show.html.erb
Restaurant : <%= @eatery.name %><br>
Open Hours : <%= @eatery.openhour %><br>
Contact : <%= @eatery.callnumber %><br>
Style  : <%= @eatery.style %><br>
Menu  : <%#= h(@eatery.menu).gsub(/\n/, '<br/>').html_safe%>

<%=image_tag "#{@eatery.image}", class: "responsive-img"%><br>

<%=link_to 'list', eateries_path, class: 'waves-effect waves-light btn'%>
<% if user_signed_in? %>
  <%# if @eatery.updatable_by? current_user %>
    <%=link_to 'edit', edit_eatery_path(@eatery), class: 'waves-effect waves-light btn'%>
  <%#end%>
  <%# if @eatery.deletable_by? current_user %>
    <%=link_to 'delete', eatery_path(@eatery), :method=> :delete, class: 'waves-effect waves-light btn'%><br>
  <%#end%><br><br>


<!--menu, review(comment), favorite, like-->
Review<br>
<% @eatery.comments.each do |c| %>
  <%= c.content %> - <%= c.user.email if c.user %><br>

    <% if c.updatable_by? current_user %> 
      <%=link_to 'edit', edit_comment_path(c), class: 'waves-effect waves-light btn'%>
    <%end%>
    <% if c.deletable_by? current_user %>
      <%=link_to 'delete', comment_path(c), method: "delete", class: 'waves-effect waves-light btn'%><br> 
    <%end%>
  <% end %>
<%end%>  <br>
  <%= render partial: 'comments/new', locals: { :comment => @eatery.comments.new , eatery: @eatery.id, belong: "eatery"} %>