config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :ricetudies
  resources :comments
  get 'home/index'
  root to: 'home#index'
  
  resources :eateries do
    post "/like", to: "likes#like_toggle"
  end
  
  resources :promotions do
    post "/like", to: "likes#like_toggle2"
  end

end

app/models/ricetudy.rb
class Ricetudy < ActiveRecord::Base
     resourcify
  include Authority::Abilities
    mount_uploader :image, AvatarUploader
    has_many :comments
    belongs_to :user

end

app/controllers/ricetudies_controller.rb
class RicetudiesController < ApplicationController
    def index
        @ricetudies = Ricetudy.paginate(:page => params[:page], :per_page => 10)
    end
    
    def new
        @ricetudy = Ricetudy.new
    
    end
    
    def create
        @ricetudy = Ricetudy.new(ricetudy_params)
        @ricetudy.user = current_user
        @ricetudy.save
        redirect_to ricetudies_path
    end
    
    def show
        @ricetudy = Ricetudy.find(params[:id])
    end
    
    def edit
        @ricetudy = Ricetudy.find(params[:id])
        authorize_action_for @ricetudy
    end
    
    def update
        @ricetudy = Ricetudy.find(params[:id])
        authorize_action_for @ricetudy
        @ricetudy.update(ricetudy_params)
        redirect_to ricetudy_path(@ricetudy)
    end
    
    def destroy
        @ricetudy = Ricetudy.find(params[:id])
        authorize_action_for @ricetudy
        @ricetudy.destroy
        redirect_to ricetudies_path
    end
    
    private
    def ricetudy_params 
    params.require(:ricetudy).permit(:title, :eatery, :start, :end_at, :content, :contact, :image)
    end
    
end

app/helpers/ricetudies_helper.rb
module RicetudiesHelper
end

app/views/ricetudies/_form.html.erb
<div class="field">
<%=f.label :title  %>
<%=f.text_field :title%>
</div>

<div class="field">
<%=f.label :restaurant  %>
<%=f.text_field :eatery%>
</div>

<div class="field">
<%=f.label :start  %>
<%=f.datetime_field :start%>
</div>

<div class="field">
<%=f.label :end  %>
<%=f.datetime_field :end_at%>
</div>

<div class="field">
<%=f.label :content  %>
<%=f.text_field :content%>
</div>

<div class="field">
<%=f.label :contact  %>
<%=f.text_field :contact%>
</div>

<div class="field">
<%=f.label :image  %>
<%=f.file_field :image%>
</div>

<%=f.submit 'write', class: 'waves-effect waves-light btn'%>

app/views/ricetudies/edit.html.erb
<%=form_for @ricetudy, multipart: true do |r| %>
<%=render partial: 'form', locals: {:f=>r}%>
<%end%>

app/views/ricetudies/index.html.erb
<%=link_to "new", new_ricetudy_path ,class: 'waves-effect waves-light btn'%><br>
  <%@ricetudies.each do |r|%>
    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <!--<img src="#{<%#=r.image%>}">-->
        </div>
        <div class="card-content">
           <span class="card-title"><%=r.title%></span><br>
          <p><%=r.content%></p>
        </div>
        <div class="card-action">
          <% unless r.user.nil? %>
            user: <%=r.user.email%><br>
          <%end%>
            eatery: <%=r.eatery%><br>
            start: <%=r.start%><br>
            end: <%=r.end_at%><br>
            contact: <%=r.contact%><br>
              
          <%=link_to "show", ricetudy_path(r), class: 'waves-effect waves-light btn'%>
          </div>
        </div>
      </div>
  <%end%>      
      <%= will_paginate @ricetudies %>

app/views/ricetudies/new.html.erb
<div class="row">
<%= form_for @ricetudy, multipart: true do |a| %>
<%=render partial: 'form', locals: {:f=> a}%>
<%end%>
</div>

app/views/ricetudies/show.html.erb
Title : <%=@ricetudy.title%><br>
Place : <%#=@ricetudy.eatery%><br>
Start : <%=@ricetudy.start%><br>
End : <%=@ricetudy.end_at%><br>
Content : <%=@ricetudy.content%><br>
Image : <%=@ricetudy.image%><br>
Contact : <%=@ricetudy.contact%><br>

<%=link_to 'list', ricetudies_path, class: 'waves-effect waves-light btn'%>
<% if user_signed_in? %>
  <% if @ricetudy.updatable_by? current_user %>
    <%=link_to 'edit', edit_ricetudy_path(@ricetudy), class: 'waves-effect waves-light btn'%>
  <%end%>    
  <% if @ricetudy.deletable_by? current_user %>
    <%=link_to 'delete', ricetudy_path(@ricetudy), method: "delete", class: 'waves-effect waves-light btn'%><br>
  <%end%><br><br>
  
<!--menu, review(comment), favorite, like-->
Review<br>
<% @ricetudy.comments.each do |c| %>
  <%= c.content %> - <%= c.user.email if c.user %><br>
    <% if c.updatable_by? current_user %>
      <%=link_to 'edit', edit_comment_path(c), class: 'waves-effect waves-light btn'%>
    <% end %>
    <% if c.deletable_by? current_user %>
      <%=link_to 'delete', comment_path(c), method: "delete", class: 'waves-effect waves-light btn'%><br> 
    <% end %>
  <%end%>
<%end%><br>
  <%= render partial: 'comments/new', locals: { :comment => @ricetudy.comments.new , eatery: @ricetudy.id, belong: "ricetudy"} %>