config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :ricetudies
  resources :comments
  get 'home/index'
  root to: 'home#index'
  
  resources :eateries do
    post "/like", to: "likes#like_toggle"
  end
  
  resources :promotions do
    post "/like", to: "likes#like_toggle2"
  end

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
     resourcify
  include Authority::Abilities

    mount_uploader :image, AvatarUploader
    #Promotion:Comment => 1:N
    has_many :comments
    #User:Promotion => 1:N
    belongs_to :user
    #Promotion:Like => 1:N
    has_many :likes
    
    # Eatery : Promotion => 1:N
    belongs_to :eatery
    
    #User:Promotion => M:N
    has_many :liked_user, through: :likes, source: :user

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
    def index
        @promotions = Promotion.paginate(:page => params[:page], :per_page => 10)
    end

    def new
        @promotion = Promotion.new
    end

    def create
        @promotion = Promotion.new(promotion_params)
        @promotion.user=current_user
        @eatery = Eatery.where(name: @promotion.restaurant)
        @promotion.eatery_id = @eatery.ids[0]
        @promotion.save
        redirect_to promotion_path(@promotion)
    end
    
    def edit
        @promotion = Promotion.find(params[:id])
        authorize_action_for @promotion
    end

    def update
        @promotion = Promotion.find(params[:id])
        authorize_action_for @promotion
        @promotion.update(promotion_params)
        redirect_to promotion_path(@promotion)
    end
    
    def show
        @promotion = Promotion.find(params[:id])
        
    end

    def destroy
        @promotion = Promotion.find(params[:id])
        authorize_action_for @promotion
        @promotion.destroy
        redirect_to promotion_path
    end
    
    private
    def promotion_params
        params.require(:promotion).permit(:name, :content, :image, :restaurant)
    end
    
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<div class="field">
<div class="field">
<%=f.label :restaurant  %>
<%=f.text_field :restaurant%>
</div>

<%=f.label :name  %>
<%=f.text_field :name%>
</div>

<div class="field">
<%=f.label :content  %>
<%=f.text_field :content%>
</div>

<div class="field">
<%=f.label :image  %>
<%=f.file_field :image%>
</div>

<%=f.submit "UPLOAD" %>

app/views/promotions/edit.html.erb
<%= form_for @promotion, multipart: true do |p|%>
<%=render partial:'form', locals: {:f=>p}%>
<%end%>

app/views/promotions/index.html.erb
<%=link_to "new", new_promotion_path ,class: 'waves-effect waves-light btn'%><br>

  <!--<div class="row">-->
    <% @promotions.each do |p| %>
        <div class="col s12 m3">
          <div class="card">
            <div class="card-image">
            <%= image_tag "#{p.image}", :size => '200x150' %>
            </div>
            <div class="card-content">
              <span class="card-title"><%=p.name%></span><br>
               <%= p.likes.size %>명이 좋아합니다.
              <% if user_signed_in? %>
                <% if current_user.is_like2(p)%>
                  <%= link_to promotion_like_path(p), method: "post" do%>
                  <%= image_tag "#{asset_path "heart.png"}", alt: "blog-img"%>
                  <%end%>
                <%else%>
                  <%= link_to promotion_like_path(p), method: "post" do%>
                  <%= image_tag "#{asset_path "heart_empty.png"}", alt: "blog-img"%>
                  <%end%>
                <%end%>
              <%end%>
              <p><%=p.content%><br></p>
            <!--</div>-->
            <div class="card-action">
              <% unless p.user.nil? %>
              user: <%=p.user.email%><br>
              <%end%>

          <%=link_to "show", promotion_path(p), class: 'waves-effect waves-light btn'%>
      
            </div>
          </div>
        </div>
      </div>
    <%end%>
            <%= will_paginate @promotions %>

app/views/promotions/new.html.erb
<div class="row">
<%= form_for @promotion, multipart: true do |a| %>
<%=render partial: 'form', locals: {:f=> a}%>
<%end%>
</div>

app/views/promotions/show.html.erb
Restaurant : <%= @promotion.name %><br>
Content  : <%= @promotion.content %>
<image_tag></image_tag><br>

<%=link_to 'list', promotions_path, class: 'waves-effect waves-light btn'%>

<% if user_signed_in? %>
  <% if @promotion.updatable_by? current_user %>
    <%=link_to 'edit', edit_promotion_path(@promotion), class: 'waves-effect waves-light btn'%>
  <%end%>
  <% if @promotion.deletable_by? current_user %>
    <%=link_to 'delete', promotion_path(@promotion), method: "delete", class: 'waves-effect waves-light btn'%><br>
  <%end%><br><br>

<!--menu, review(comment), favorite, like-->
Review<br>
<% @promotion.comments.each do |c| %>
  <%= c.content %> - <%= c.user.email if c.user %><br>
    <% if c.updatable_by? current_user %>
      <%=link_to 'edit', edit_comment_path(c), class: 'waves-effect waves-light btn'%>
    <% end %>
    <% if c.deletable_by? current_user %>
      <%=link_to 'delete', comment_path(c), method: "delete", class: 'waves-effect waves-light btn'%><br> 
    <% end %>
  <%end%>
<% end %><br>  
  <%= render partial: 'comments/new', locals: { :comment => @promotion.comments.new , promotion: @promotion.id, belong: "promotion"} %>
  
  